site_name: Rujta Dev Docs
site_description: Documentation for my .NET 8 + React project
site_author: Mohamed Ahmad
docs_dir: '.'
site_dir: '../site'
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Rujta Project Structure: rujta_project_structure.md
  - API Reference: api_reference.md
  - Frontend Guide: frontend_guide.md
  
theme:
  name: material